### ISSUE TITLE
Stolen Code

### ISSUE THREAD

**Issue by CrunchyRLL** [FunctionDJ/omori_de#4]
Stolen banning ppl on their discord for no reason Im gonna steal my code back and make the 100% Translation with my 91 Member Team

**Comment by FunctionDJ** [comment]
@omoridepressed stealing? banning? what translation?
i'd really like to sort out whatever issue there is. you can send me a FR at Function#5603 and we can talk about this.

**Comment by FunctionDJ** [comment]
your translations are not even in this repo lmao. go ahead and "steal" from an open source project you script kiddie.
how about you grow up and stop getting banned
